### ISSUE TITLE
Make GitHub Link more prominent

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/website#48]
@sebastiankb feels like it is difficult to find/see the GitHub Link (at the moment present in footer and prose).
How can we improve the situation? Have its "own" navigation item?

@egekorkan others opinions?

We plan to rework the structure & content of the Website anyway..

**Comment by relu91** [comment]
I think that probably we need to place it at the upper right corner as other websites. A general rework of the website could simply take this in mind.

**Comment by danielpeintner** [comment]
Moreover, we should no longer use
https://github.com/eclipse-thingweb/node-wot
but instead point to generic repo
https://github.com/eclipse-thingweb
which lists all projects
