### ISSUE TITLE
Examples Web Page

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/website#61]
We also have a page at http://plugfest.thingweb.io/examples/smart-coffee-machine.html . We should decide where it  should be versioned.

**Comment by JKRhb** [comment]
Could it be that the HTTP Test Things are currently offline? Seems like it is at least not possible to retrieve the TDs using HTTP.

**Comment by danielpeintner** [comment]
> Could it be that the HTTP Test Things are currently offline? Seems like it is at least not possible to retrieve the TDs using HTTP.

Do you mean http://plugfest.thingweb.io:8083/counter and such?
Seems to work for me...

**Comment by JKRhb** [comment]
> > Could it be that the HTTP Test Things are currently offline? Seems like it is at least not possible to retrieve the TDs using HTTP.
> 
> Do you mean http://plugfest.thingweb.io:8083/counter and such? Seems to work for me...

Strange, it now works for me again as well 🤔 Maybe it was just a temporary issue – thank you for the quick feedback :)

**Comment by egekorkan** [comment]
This is not relevant anymore, closing
