### ISSUE TITLE
404 page misses to load CSS properly

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/website#63]
I am pretty sure we once had a more or less page showing that a page does no longer exist.

Now, this is no longer the case and we have something like this, try for example https://www.thingweb.io/foo/

![image](https://github.com/eclipse-thingweb/website/assets/11281461/1a235156-aa07-4eee-80d3-1e932ea71faa)

**Comment by egekorkan** [comment]
https://github.com/eclipse-thingweb/website/pull/64 has tried to fix it but it is not fixed yet. We need to investigate inner workings more.

**Comment by danielpeintner** [comment]
It seems the main issue is that the CSS etc is searched in the wrong folder ... e.g., https://www.thingweb.io/foo/

![image](https://github.com/eclipse-thingweb/website/assets/11281461/9d9d182f-4200-424e-abad-e01605477c51)

**Comment by danielpeintner** [comment]
It seems related to https://github.com/gohugoio/hugo/issues/1555#issuecomment-1679247567
