### ISSUE TITLE
Rework the "News" page

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/website#72]
Our [news](https://www.thingweb.io/news.html) page is regularly out-of-date.

Having said that, I don't  think we should any longer maintain our _own_ news page. We could simply point to other resources like Mastodon/X, Stackoverflow and WoT Wiki pages instead.

OR

remove the page all together.

Any thoughts/ideas/proposals?

**Comment by egekorkan** [comment]
Sort of duplicate of #56. I propose we continue the discussion there
