### ISSUE TITLE
Implementation of a cookie/consent button for consent management

### ISSUE THREAD

**Issue by SergioCasCeb** [eclipse-thingweb/website#75]
Once the consent banner is hidden it might be difficult for users to find the "Manage Cookies" link in the footer. Anyhow, I don't have a good alternative other than creating a dedicated cookie button in the bottom right corner or so... not sure if this might work better.

An example what I mean can be seen on
https://www.cookieyes.com/documentation/change-cookie-consent-using-cookieyes/

_Originally posted by @danielpeintner in https://github.com/eclipse-thingweb/website/issues/74#issuecomment-2060537796_

**Comment by SergioCasCeb** [comment]
I am guessing this is not relevant anymore right @egekorkan?

**Comment by egekorkan** [comment]
This is still relevant, I think. @danielpeintner what do you think?

**Comment by danielpeintner** [comment]
Mhh, the *current* page at https://www.thingweb.io **has** the consent footer. Hence I assume we can close the issue..

**Comment by egekorkan** [comment]
alright, closing
