### ISSUE TITLE
Improve the get involved page 

### ISSUE THREAD

**Issue by relu91** [eclipse-thingweb/website#76]
It seems that the get involved page is the second most viewed page on our website. It is already good but we could add for example links to our social accounts (Discord and Telegram) to get some traffic also there.

**Comment by egekorkan** [comment]
The whole website can/should be improved and we should discuss this soon. Also, I would wait maybe a month or so before taking any data-driven decisions. At the moment, it could be just us clicking around to test everything (countries list show otherwise though)

**Comment by egekorkan** [comment]
Not relevant anymore

**Comment by danielpeintner** [comment]
Mhh, not sure but on the *new*page we miss some call to developers to be active.

I still think some information from http://web.archive.org/web/20240222120722/https://www.thingweb.io/get-involved.html could be of interest on the main page or on a dedicated sub-page?

**Comment by SergioCasCeb** [comment]
I also think it could be useful to have a get involved sub page, and provide a cta as well on the main landing page.

**Comment by egekorkan** [comment]
We had a chat about this today. We can create such a page and explain in detail stuff like trying out an example, playground etc., chatting (discord and telegram), creating issues etc., joining the calls

**Comment by egekorkan** [comment]
Also done as of #103
