### ISSUE TITLE
[enhancement] Add PR review bot

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/website#9]
Similar to the way w3c repositories generate a static page for every PR, it would be nice to add a bot that does this for this repository. This might however need the involvement of someone from the Eclipse Foundation.

**Comment by danielpeintner** [comment]
While I agree that an automatic and online process would be beneficial the process to *check* PRs locally is not a big deal either if hugo is setup properly

1. check out PR
2. run `hugo server -D` and check result

**Comment by egekorkan** [comment]
A Netlify preview is added at https://thingweb-preview.netlify.app/ . Subsequent PRs should trigger PR previews to be generated

**Comment by danielpeintner** [comment]
I opened https://github.com/eclipse-thingweb/website/pull/51 and there is no preview shown...
